<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260319095720 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE countries (code VARCHAR(2) NOT NULL, name_en VARCHAR(255) NOT NULL, name_local VARCHAR(255) NOT NULL, primary_language VARCHAR(10) NOT NULL, flag_emoji VARCHAR(5) NOT NULL, suicide_illegal BOOLEAN DEFAULT false NOT NULL, police_dispatch_risk BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE crisis_resources (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, text_number VARCHAR(255) DEFAULT NULL, is24h BOOLEAN NOT NULL, is_free BOOLEAN NOT NULL, no_police_by_default BOOLEAN DEFAULT false NOT NULL, is_primary BOOLEAN DEFAULT false NOT NULL, languages JSON DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, country_code VARCHAR(2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E4163990F026BB7C ON crisis_resources (country_code)');
        $this->addSql('CREATE TABLE followup_queue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email_hash VARCHAR(64) NOT NULL, encrypted_email TEXT NOT NULL, country_code VARCHAR(2) NOT NULL, locale VARCHAR(10) NOT NULL, send_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sent BOOLEAN DEFAULT false NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3401B274E8E423D ON followup_queue (email_hash)');
        $this->addSql('ALTER TABLE crisis_resources ADD CONSTRAINT FK_E4163990F026BB7C FOREIGN KEY (country_code) REFERENCES countries (code) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE crisis_resources DROP CONSTRAINT FK_E4163990F026BB7C');
        $this->addSql('DROP TABLE countries');
        $this->addSql('DROP TABLE crisis_resources');
        $this->addSql('DROP TABLE followup_queue');
    }
}
