home_root:
    path: /
    controller: App\Controller\HomeController::root

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: de|en|ru|ko|ja|lt|uk|es
    defaults:
        _locale: en
